version: '3.1'

services:
  db:
    image: mysql:latest
    restart: always
    container_name: sg_laravel
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sg
      MYSQL_USER: my-patrick
      MYSQL_PASSWORD: docker
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "5001:3306"

volumes:
  mysql_data:
    name: mysql_data_laravel
